{% set name = "infomeasure" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/infomeasure-{{ version }}.tar.gz
  sha256: b290fe896aec71b55864acbee53456f046d4cae0b7da1ea23950a7dfa2d985fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - sparse >0.10.0

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  imports:
    - infomeasure
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  summary: Comprehensive collection of information measures.
  description: |
    infomeasure in a Python package for calculating various information measures,
    including entropy, mutual information, transfer entropy, and more, with support
    for both discrete and continuous variables.
  home: https://infomeasure.readthedocs.io/
  license: AGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://infomeasure.readthedocs.io/
  dev_url: https://github.com/cbueth/infomeasure

extra:
  recipe-maintainers:
    - cbueth
